### ISSUE TITLE
Changing a venue location throws

### ISSUE THREAD

**Issue by axunonb** [axuno/Volleyball-League#35]
Trying to enter a new venue or making changes to the venue location (postal code, city, street) will result in an `System.Data.SqlClient.SqlException (0x80131904): Could not find stored procedure 'dbo.VenueDistance'.`
[Support ticket](https://www.llblgen.com/tinyforum/Thread/27471/1) opened for LlblGenPro.

**Comment by axunonb** [comment]
[Bug fix for LlblGenPro](https://www.llblgen.com/tinyforum/Thread/27471) fixed this issue. Commit# https://github.com/axuno/Volleyball-League/commit/e31e3dd7ec528427b5bdc08283f4daf491a22671

**Comment by imprima** [comment]
Commit [Various fixes](]https://github.com/axuno/Volleyball-League/commit/2ebaf9f2323404a35b8edbd9746fc37bdb5a1ba9) did not fix this issue.
