### ISSUE TITLE
"MyTeam" for a team contact only shows the headline

### ISSUE THREAD

**Issue by imprima** [axuno/Volleyball-League#51]
Having a look at the page HTML source in the browser, all expected data is included, but hidden.

**Comment by axunonb** [comment]
This happens here 

https://github.com/axuno/Volleyball-League/blob/fdd641be2e2e31f2febe62de85c810c51cbc92c6/League/Views/Team/MyTeam.cshtml#L45

when the `Model.ActiveTeamId` contains a value that is not included in `Model.TeamVenueRoundInfos[x].TeamId`
