### ISSUE TITLE
Configuration changes during runtime should take immediate effect

### ISSUE THREAD

**Issue by imprima** [axuno/Volleyball-League#57]
Modify handling of configuration file changes as described in these posts:

Using `IOptionsSnapshot`:
https://edi.wang/post/2019/1/5/auto-refresh-settings-changes-in-aspnet-core-runtime

Using `IOptionMonitor`:
https://medium.com/@niteshsinghal85/configuration-change-detection-with-ioptionmonitor-in-asp-net-core-e26b71cfdb2f

**Comment by axunonb** [comment]
Resolved with #86
